### ISSUE TITLE
Internalize `RotationAxis` property

### ISSUE THREAD

**Issue by cjsha** [open-ephys/bonsai-commutator#10]
I propose that any rotation axis transformation should be performed in software by sending commands to the BNO055, and not be compensated for in the auto commutator node. I'm not sure what the added benefit is when the correct `RotationAxis` setting to work with all our headstages is supposed to be "0,0,1" anyway. I feel like this only makes commutator workflows more prone to errors. I might be missing something about why it's important to keep that property externalized though.

**Comment by jonnew** [comment]
Probably correct 

The reason is to compensate for some bno data in which orientation is not standardized with positive z axis pointing along tether. We could say that the autocommutator expects this condition and it's up to source to make sure it's the case.
