### ISSUE TITLE
AutoCommutator node can hang in some machines

### ISSUE THREAD

**Issue by aacuevas** [open-ephys/bonsai-commutator#8]
It has been observed that in some machines, the SerialWriteLine node seems to be overwhelmed and causes the whole Bonsai workflow to freeze. Reducing the data rate seems to solve this. We have tested:
- Removing the 0-turn commands as in #7 seem to solve this issue
- Increasing the sample interval to >0.3s seems to also solve this issue

This seems to be a buffer-overflow related issue, unclear if it stems on the software side or the the UART-over-USB hardware side on the commutator.

A very annoying consequence is that, when this happens, workflow cannot be stopped. Even closing the Bonsai window keeps a background process open that cannot be even killed from the task manager, which keeps all resources open. Unplugging the commutator (thus, force-closing the COM port) causes an exception but allows the Bonsai process to fully close. ( @glopesdev please advise if a Bonsai issue report would be useful. It feels like unwanted behavior for the `SerialWriteLine` node, although is unclear how much of it might be the kernel USB-UART driver responsibility)

**Comment by jonnew** [comment]
I've seen this issue as well. There was a user who could only reliably send commands at 5 hz. Beyond that and communication would stop after 10s of commands and halt bonsai, requiring a restart.

This is a critical issue. We will need to find a more reliable method for communication with the device.

**Comment by jonnew** [comment]
One more thing - we are switching the commutator mcu from teensy to rp2040, which I believe uses a completely diffent driver.

**Comment by jonnew** [comment]
Also could just implement as usb device:

https://github.com/raspberrypi/pico-examples/tree/master/usb/device

**Comment by aacuevas** [comment]
@ChucklesOnGitHub and I have planned to run some tests and try to reproduce the issue without an onix system to characterize it. That will give us more information on the failure point.

In the meanwhile, #7 seems to, apparently, solve the issue. We added that condition and then could run the workflow for a little while while moving the commutator without issues. Admittedly, we did not run a full long test. 

In any case, we will have more information if we manage to reproduce the freeze independent of onix.

**Comment by aacuevas** [comment]
We have done more tests, and I am starting to suspect some kind of race condition on Bonsai's `SerialWriteLine` instead of an issue on the commutator itself.
Namely:
- We have created a non-onix workflow that blasts data to the commutator at a rate 4 times higher than the `AutoCommutator` node is, and we haven't been able to produce a freeze. This includes mixes of 0-turns and 0.1-turns
- After more extensive testing, #7 does not seem to fully resolve the issue, but just reducing the chances of it happening. Same with reducing the command rate
- Freezes seem independent of the turn commands, they can happen with just a bunch of 0-turns
- Debugging a freeze, without Bonsai symbols atm, shows a thread waiting on something like `System.IO.Serial.End` (I forgot to copy the full name) while there is another thread with something like `WaitForSerialEvent` in the serial node.

While it's not definitive proof, These do align with my current suspicions. Moreso since a ONIX workflow is thread-heavy, which could be causing a race condition which rarely hits in less thread-intensive applications.

Any ideas on how to continue debugging to discard or confirm where to look?

**Comment by aacuevas** [comment]
Yeah, at first the 0-turn seemed to work and I thought it was alleviating some buffer on the communication channel, but more expensive testing suggest is just that, less chance of the issue appearing.

Looking around the net there seems to be lots of people complaining about `IO.Ports.SerialPort` so I would not discard there being a weird issue with the .NET implementation itself... What I am unsure of is how to implement a serial port writer in C# independent of it, but creating a very simple serial writer does not seem like a bad idea, at least for now.

This is indeed a critical issue and requires a fast solution.

**Comment by jonnew** [comment]
It turns out this was due to an old issue that was solved in firmware: the commutator firmware really does not like receiving a {turn:nan} motion command. This was solved in version 1.6 of the firmware, but there are commutators in the field without this fix. #11 Now performs software filtering of Nan and Infinity values for added protection
